[package]
name = "poker-app"
version = "0.1.0"
edition = "2024"

[dependencies]
sails-rs = "0.8.0"
gstd = { version = "1.8.0", features = ["debug"] }
gbuiltin-bls381 = "1.8.0"
hex-literal = "0.4.1"
ark-ed-on-bls12-381-bandersnatch = { version = "0.5", default-features = false }