name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

defaults:
  run:
    working-directory: contracts

jobs:
  build-and-publish:
    name: Build and Publish Artifacts
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32v1-none
        override: true

    - name: Install Clippy
      run: rustup component add clippy

    - name: Install Rustfmt
      run: rustup component add rustfmt

    - name: Install rust-src component
      run: rustup component add rust-src --toolchain stable-x86_64-unknown-linux-gnu

    - name: Check formatting
      run: cargo fmt --all --check

    - name: Run Clippy
      run: cargo clippy -r --all -- -D warnings

    - name: Run tests
      run: cargo test -r

    - name: Build project
      run: cargo build --release

    - name: Prepare artifacts directory
      run: |
        mkdir -p artifacts
        cp target/wasm32-gear/release/*.wasm artifacts/
        cp target/wasm32-gear/release/*.idl artifacts/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wasm-artifacts
        path: artifacts/
