name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

defaults:
  run:
    working-directory: contracts
env:
  CARGO_TERM_COLOR: always
  GEAR_VERSION: 1.8.1

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.88.0
        components: rustfmt,clippy
        targets: wasm32v1-none

    - name: Install rust-src component
      run: rustup component add rust-src --toolchain 1.88.0-x86_64-unknown-linux-gnu

    - name: Prepare Gear Binary
      run: |
        mkdir -p target/tmp
        wget -qO- https://get.gear.rs/gear-v${{ env.GEAR_VERSION }}-x86_64-unknown-linux-gnu.tar.xz | tar xJ -C target/tmp

    - name: Fmt
      run: cargo fmt --all -- --config imports_granularity=Crate,edition=2021

    - name: Clippy
      run: cargo clippy --release --workspace --all-targets --all-features -- -D warnings
        
    - name: Test
      run: cargo test --release
