name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

defaults:
  run:
    working-directory: contracts

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32v1-none
        override: true

    - name: Install tools (binaryen + clang/lld)
      run: |
        sudo apt-get update
        sudo apt-get install -y binaryen clang lld

    - name: Install Clippy
      run: rustup component add clippy

    - name: Install Rustfmt
      run: rustup component add rustfmt

    - name: Install rust-src component
      run: rustup component add rust-src --toolchain stable-x86_64-unknown-linux-gnu

    - name: Check formatting
      run: cargo fmt --all --check

    - name: Run Clippy
      run: cargo clippy -r --all -- -D warnings

    - name: Print toolchain/env (diagnose)
      run: |
        rustc -vV
        cargo -vV
        rustup show
        cc --version || true
        ld --version || true
        uname -a
        cat /etc/os-release
        
    - name: Run tests (host via clang+lld)
      env:
        CC: clang
        CXX: clang++
        RUSTFLAGS: "-Clinker=clang -Clink-arg=-fuse-ld=lld -Cforce-frame-pointers=yes"
      run: cargo test -r

    - name: Build project
      run: cargo build --release

    - name: Prepare artifacts directory
      run: |
        mkdir -p artifacts
        cp target/wasm32-gear/release/*.wasm artifacts/ || true
        cp target/wasm32-gear/release/*.idl artifacts/ || true

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wasm-artifacts
        path: artifacts/
